# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jld4mJsBUQcs1qbbUJj9AXnPn-jMeTMX
"""

# Filename: calculate_volatility.py

import pandas as pd
import numpy as np

def calculate_daily_returns(close_prices):
    return close_prices.pct_change()

def calculate_daily_volatility(daily_returns):
    return np.std(daily_returns)

def calculate_annualized_volatility(daily_volatility, length_of_data):
    return daily_volatility * np.sqrt(length_of_data)

def main():
    # Load data from the CSV file
    data = pd.read_excel('NIFTY 50.xlsx')

    # Print column names to identify the correct column for closing prices
    print("Column Names:", data.columns)

    # Assuming the dataset has a column for closing prices, replace 'Close' with the correct column name
    close_prices = data['Close ']  # Replace 'Correct_Column_Name' with the actual column name

    # Calculate daily returns
    daily_returns = calculate_daily_returns(close_prices)

    # Calculate daily volatility
    daily_volatility = calculate_daily_volatility(daily_returns)

    # Calculate annualized volatility
    length_of_data = len(data)
    annualized_volatility = calculate_annualized_volatility(daily_volatility, length_of_data)

    # Print results
    print(f'Daily Volatility: {daily_volatility:.4f}')
    print(f'Annualized Volatility: {annualized_volatility:.4f}')

if __name__ == "__main__":
    main()

